version: '3'

services:
  react-ts-starter-template:
    container_name: react-ts-starter-template
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${VITE_PORT}:${VITE_PORT}
